name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Debug SSH Connection
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        echo "Host: $HOST"
        echo "Username: $USERNAME"
        ssh -i ${{ secrets.PRIVATE_KEY }} $USERNAME@$HOST echo "SSH connection successful"
    - name: Deploy using ssh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/apps/comproatm
          git pull origin main
          git status
          npm install --only=prod
          npm run build
