name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa-github-actions-nodejs
        chmod 600 ~/.ssh/id_rsa-github-actions-nodejs

    - name: Debug SSH Key
      run: ls -al ~/.ssh

    - name: Deploy using ssh
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ~/.ssh/id_rsa-github-actions-nodejs
        port: 22
        script: |
          cd ~/apps/comproatm
          git pull origin main
          git status
          npm install --only=prod
          npm run build
